# Generated by Django 5.2.3 on 2025-06-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_number', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('guarantee_type', models.CharField(choices=[('DO', 'DO seule'), ('TRC', 'TRC seule'), ('DUO', 'DO + TRC')], default='DO', max_length=20)),
                ('destination', models.CharField(choices=[('housing', 'Habitation'), ('non_housing', 'Hors habitation')], default='housing', max_length=50)),
                ('work_type', models.CharField(choices=[('light_reno', 'Rénovation légère'), ('heavy_reno', 'Rénovation lourde'), ('new_build', 'Ouvrage neuf')], default='light_reno', max_length=50)),
                ('has_existing_building', models.BooleanField(default=False)),
                ('is_vip_client', models.BooleanField(default=False)),
                ('wants_rcmo', models.BooleanField(default=False)),
                ('construction_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
